<?php
return array (
  'site_title' => 'DarsiPro CMS',
  'meta_keywords' => 'создание сайта, шаблоны',
  'meta_description' => 'Что такое и как пользоваться DarsiPro CMS. Документация и шаблоны',
  'title' => 'DarsiPro CMS - простота и легкость создания сайтов',
  'language' => 'rus',
  'permitted_languages' => 'rus,eng',
  'cache' => 0,
  'announce_lenght' => '1000',
  'cookie_time' => '30',
  'start_mod' => '',
  'debug_mode' => 0,
  'max_file_size' => 14999552,
  'IEC60027-2' => 1,
  'admin_email' => 'no-reply@email.cms',
  'redirect' => '',
  'redirect_delay' => '1',
  'template' => 'default',
  'templates_cache' => 1,
  'hlu' => 1,
  'hlu_extention' => '.htm',
  'hlu_understanding' => 0,
  'allow_html' => 0,
  'date_format' => 'j F Yг. в G:i',
  'use_watermarks' => 1,
  'watermark_img' => 'watermark.png',
  'quality_jpeg' => '100',
  'quality_png' => '',
  'watermark_hpos' => '3',
  'watermark_vpos' => '3',
  'watermark_alpha' => '50',
  'watermark_type' => '',
  'watemark_min_img' => '200',
  'watermark_text' => 'DarsiPro',
  'watermark_text_angle' => '',
  'watermark_text_size' => '10',
  'watermark_text_color' => 'FFFFFF',
  'watermark_text_border' => '808080',
  'watermark_text_font' => 'Scada-Bold.ttf',
  'watermark_indent' => '5',
  'raw_time_mess' => '300',
  'auto_sitemap' => 1,
  'allow_smiles' => 1,
  'smiles_set' => 'drspro',
  'use_preview' => 1,
  'img_size_x' => '450',
  'img_size_y' => '450',
  'video_size_x' => '500',
  'video_size_y' => '300',
  'use_noindex' => 1,
  'hide_method' => '2',
  'use_ignoring' => 0,
  'use_multicategories' => 0,
  'comments_tree' => 0,
  'tables_with_addfields' =>
  array (
    0 => 'comments',
  ),
  'system_modules' =>
  array (
    0 => '__sys__',
    1 => '__seo__',
    2 => '__secure__',
    3 => '__rss__',
    4 => '__sitemap__',
    5 => '__preview__',
    6 => '__watermark__',
    7 => '__db__',
  ),
  'installed_modules' =>
  array (
    0 => 'news',
    1 => 'stat',
    2 => 'loads',
    3 => 'forum',
    4 => 'users',
    5 => 'foto',
    6 => 'chat',
    7 => 'pages',
    8 => 'search',
    9 => 'statistics',
  ),
  'news_on_home' => 1,
  'cnt_latest_on_home' => '5',
  'latest_on_home' =>
  array (
    'news' => 'news',
    'stat' => 'stat',
    'loads' => 'loads',
  ),
  '__secure__' =>
  array (
    'antisql' => 0,
    'anti_ddos' => 0,
    'request_per_second' => '7',
    'system_log' => 1,
    'max_log_size' => 99999744,
    'autorization_protected_key' => 0,
    'session_time' => 7200,
  ),
  '__rss__' =>
  array (
    'rss_news' => 1,
    'rss_stat' => 1,
    'rss_loads' => 1,
    'rss_forum' => 1,
    'rss_lenght' => 300,
    'rss_cnt' => 10,
  ),
  '__db__' =>
  array (
  ),
)
?>